# ===== Banco de dados (SQLite) =====
spring.datasource.url=jdbc:sqlite:toca_dos_peludos.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===== Upload de arquivos =====
# Regra de negocio 7: tamanho maximo por arquivo
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=uploads

# ===== Autenticacao (JWT) =====
app.jwt.secret=toca-dos-peludos-chave-secreta-do-mvp-academico-2026
app.jwt.expiracao-minutos=480

server.port=8080
